=== Krazick/Krazick.github.io/18XX-Game-Engine-XML/public/XSD/18XX-Corporations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" 
	elementFormDefault="qualified" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Certificate">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="FreeCertificate" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="director" use="optional"/>
      <xs:attribute type="xs:byte" name="percentage" use="optional"/>
      <xs:attribute type="xs:string" name="allowedOwners" use="optional"/>
      <xs:attribute type="xs:byte" name="quantity" use="optional"/>
      <xs:attribute type="xs:short" name="corporationId" use="optional"/>
      <xs:attribute type="xs:byte" name="discountAmount" use="optional"/>
      <xs:attribute type="xs:string" name="canBeBidOn" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Benefit">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="actorType" use="optional"/>
          <xs:attribute type="xs:string" name="class" use="optional"/>
          <xs:attribute type="xs:string" name="extra" use="optional"/>
          <xs:attribute type="xs:string" name="mapCell" use="optional"/>
          <xs:attribute type="xs:byte" name="cost" use="optional"/>
          <xs:attribute type="xs:string" name="passive" use="optional"/>
          <xs:attribute type="xs:string" name="closeOnUse" use="optional"/>
          <xs:attribute type="xs:string" name="sameTurn" use="optional"/>
          <xs:attribute type="xs:short" name="corporationID" use="optional"/>
          <xs:attribute type="xs:byte" name="certificatePercentage" use="optional"/>
          <xs:attribute type="xs:string" name="certificatePresident" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Benefits">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Benefit" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FreeCertificate">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:short" name="corporationId" use="optional"/>
          <xs:attribute type="xs:byte" name="percentage" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Certificate"/>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="row" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Private">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Benefits" minOccurs="0"/>
        <xs:element ref="Certificate"/>
      </xs:sequence>
      <xs:attribute type="xs:short" name="id" use="required"/>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="abbrev" use="required"/>
      <xs:attribute type="xs:short" name="cost" use="optional"/>
      <xs:attribute type="xs:string" name="note" use="optional"/>
      <xs:attribute type="xs:byte" name="revenue" use="optional"/>
      <xs:attribute type="xs:string" name="homeCell1" use="required"/>
      <xs:attribute type="xs:byte" name="homeLocation1" use="required"/>
      <xs:attribute type="xs:byte" name="homeLocation2" use="optional"/>
      <xs:attribute type="xs:string" name="special" use="optional"/>
      <xs:attribute type="xs:string" name="mustSell" use="optional"/>
      <xs:attribute type="xs:short" name="exchangeID" use="optional"/>
      <xs:attribute type="xs:byte" name="exchangePercentage" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Share">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Certificate" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:short" name="id" use="required"/>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="abbrev" use="required"/>
      <xs:attribute type="xs:string" name="homeCell1" use="required"/>
      <xs:attribute type="xs:byte" name="homeLocation1" use="required"/>
      <xs:attribute type="xs:string" name="homeCell2" use="optional"/>
      <xs:attribute type="xs:byte" name="homeLocation2" use="optional"/>
      <xs:attribute type="xs:string" name="bgColor" use="required"/>
      <xs:attribute type="xs:string" name="fgColor" use="required"/>
      <xs:attribute type="xs:byte" name="tokens" use="required"/>
      <xs:attribute type="xs:short" name="closeOnTrainPurchase" use="optional"/>
      <xs:attribute type="xs:string" name="mustBuyTrain" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="StartPacket">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Item" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Corporations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Private" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="Share" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element ref="StartPacket"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Krazick/Krazick.github.io/18XX-Game-Engine-XML/XML/1853/1853-Companies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<Corporations
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://krazick.github.io/schema 
						https://krazick.github.io/18XX-Game-Engine-XML/public/XSD/18XX-Corporations.xsd">
	<Share id="1901" name="East Indian Railway" abbrev="EIR" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Jab" homeLocation1="7" homeCell2="Hx" homeLocation2="10" homeType="both"
		bgColor="Red" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="0,14">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1902" name="Great Indian Pennisula Railway" abbrev="GIP" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Mi" homeLocation1="10" homeCell2="Ht" homeLocation2="10" homeType="both"
		bgColor="204,102,0" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="1,13">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1903" name="North Western Railway" abbrev="NWR" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Fn" homeLocation1="7" homeCell2="Ck" homeLocation2="11" homeType="both"
		bgColor="Black" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="2,12">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1904" name="Bengal Nagpur Railway" abbrev="BNR" tileLaysAllowed="2" actorBank="Corporate Bank"
		homeCell1="Kq" homeLocation1="17" homeCell2="Jab" homeLocation2="11" homeType="both"
		bgColor="Dark Green" fgColor="White" tokens="5" tokenType="FixedCost" startPrice="3,11">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1905" name="Bombay, Baroda and Central India Railway" actorBank="Corporate Bank"
		abbrev="BBCI" homeCell1="Hj" homeLocation1="15" bgColor="Deep Blue"
		fgColor="White" tokens="4" tokenType="FixedCost" startPrice="4,10">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1906" name="Madras and South Mahratta Railway" abbrev="MSM" actorBank="Corporate Bank"
		homeCell1="Rr" homeLocation1="7" bgColor="153,0,204" fgColor="Black"
		tokens="4" tokenType="FixedCost" startPrice="5,9">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1907" name="South Indian Railway" abbrev="SIR" actorBank="Corporate Bank"
		homeCell1="Tp" homeLocation1="16" bgColor="Yellow" fgColor="Black"
		tokens="4" tokenType="FixedCost" startPrice="6,8">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1908" name="Bengal Assam Railway" abbrev="BAR" actorBank="Corporate Bank"
		homeCell1="Jah" homeLocation1="12" bgColor="Light Blue" fgColor="Black"
		tokens="3" tokenType="FixedCost" startPrice="7,7">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
</Corporations>

=== Krazick/Krazick.github.io/18XX-Game-Engine-XML/XML/1830/1830-Companies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<Corporations
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://krazick.github.io/schema 
						https://krazick.github.io/18XX-Game-Engine-XML/public/XSD/18XX-Corporations.xsd">
	<Private id="1001" name="Schuylkill Valley" abbrev="SVN&amp;RR" cost="20" 
		note="No other attributes"
		revenue="5" homeCell1="G15" homeLocation1="10" homeLocation2="15" special="NONE" mustSell="true">
		<Certificate director="YES" percentage="100"
			allowedOwners="IPO,Player,Share" />
	</Private>
	<Private id="1002" name="Champlain &amp; St. Lawrence" abbrev="C&amp;SL" cost="40" 
		revenue="10" homeCell1="B20" homeLocation1="7" homeLocation2="12" 
		note="A Corporation owning the C&amp;SL may lay a tile on the C&amp;SL's hex even if this hex is not connected to the Corporation's Railhead. This free tile placement is in addition to the Corporation's tile placement — For this turn only the Corporation may play two tiles. The tile played on the C&amp;SL hex does not have to connect to any existing adjacent track."
		special="Free Tile Placement">
		<Benefits>
			<Benefit actorType="Share Company" class="ge18xx.company.benefit.TilePlacementBenefit" extra="true" mapCell="B20" cost="0" passive="false"/>
		</Benefits>
		<Certificate director="YES" percentage="100"
			allowedOwners="IPO,Player,Share" />
	</Private>
	<Private id="1003" name="Delaware &amp; Hudson" abbrev="D&amp;H"
		cost="70" revenue="15" homeCell1="F16" homeLocation1="16" homeLocation2="14" 
		note="A Corporation owning the D&amp;H may establish a Railhead on the D&amp;H’s hex by laying a station tile and a token. The station does NOT have to be connected to the remainder of the Corporation’s route. The tile layed is the owning Railroad’s one tile placement per turn. Placing a token is not required, but if placed in a future turn, it must be paid for. Removal of the mountain costs $120 as usual but there is no charge for laying the token.  (Other Corporations may lay a tile here subject to the  ordinary rules.)"
		special="Tile Placement and Token Placement">
		<Benefits>
			<Benefit actorType="Share Company" class="ge18xx.company.benefit.TilePlacementBenefit" extra="false" mapCell="F16" cost="120" passive="false"/>
			<Benefit actorType="Share Company" class="ge18xx.company.benefit.TokenPlacementBenefit" closeOnUse="false" extra="false" mapCell="F16" cost="0" sameTurn="true" passive="false"/>
		</Benefits>
		<Certificate director="YES" percentage="100"
			allowedOwners="IPO,Player,Share" />
	</Private>
	<Private id="1004" name="Mohawk &amp; Hudson" abbrev="M&amp;H"
		cost="110" revenue="20" homeCell1="D18" homeLocation1="21" homeLocation2="44"
		note="A player owning the M&amp;H may exchange it for a 10% share of NYC provided the player does not already hold 60% of the NYC stock and there is NYC stock available in the Bank or the Pool. The exchange may be made during the player’s turn of a Stock Round or between the turns of other players or Railroads in either Stock or Operating Rounds.  This action closes the M&amp;H." 
		special="Exchange for 10% of NYC">
		<Benefits>
			<Benefit actorType="Player" class="ge18xx.company.benefit.QueryExchangeBenefit" corporationID="1103" certificatePercentage="10" closeOnUse="true" passive="false"/>
		</Benefits>
		<Certificate director="YES" percentage="100"
			allowedOwners="IPO,Player,Share" />
	</Private>
	<Private id="1005" name="Camden &amp; Amboy" abbrev="C&amp;A"
		cost="160" revenue="25" homeCell1="H18" homeLocation1="15" homeLocation2="45" 
		note="The initial purchaser of the C&amp;A immediately receives a 10% share of PRR stock without further payment. This action does NOT close the C&amp;A. The PRR Corporation will not be running at this point, but the stock may be retained or sold subject to the ordinary rules of the game (see  8.1, last paragraph)."
		special="Free 10% PRR">
		<Benefits>
			<Benefit actorType="Player" class="ge18xx.company.benefit.FreeCertificateBenefit" corporationID="1101" certificatePercentage="10" passive="true"/>
		</Benefits>
		<Certificate director="YES" percentage="100"
			allowedOwners="IPO,Player,Share" />
	</Private>
	<Private id="1006" name="Baltimore &amp; Ohio" abbrev="B&amp;O"
		cost="220" revenue="30" homeCell1="I15" homeLocation1="12" homeLocation2="13" 
		note="The owner of the B&amp;O Private Company immediately receives the President’s Certificate of the B&amp;O Railroad without further payment (see 8.1). The B&amp;O Private Company may NOT be sold to any Corporation, and does not change hands if the owning player loses the Presidency of the  B&amp;O. When the B&amp;O Corporation purchases its first train the Private Company is closed down."
		special="Free President Share of B&amp;O">
		<Benefits>
			<Benefit actorType="Player" class="ge18xx.company.benefit.FreeCertificateBenefit" corporationID="1102" certificatePercentage="20" certificatePresident="true" passive="true"/>
		</Benefits>
		<Certificate director="YES" percentage="100"
			allowedOwners="IPO,Player" />
	</Private>
	<Share id="1101" name="Pennsylvania" abbrev="PRR" homeCell1="H12"
		homeLocation1="14" bgColor="Dark Green" fgColor="White" tokens="4" tokenType="FixedCost">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1102" name="Baltimore &amp; Ohio" abbrev="B&amp;O"
		homeCell1="I15" homeLocation1="21" bgColor="Deep Blue" fgColor="White"
		tokens="3"  tokenType="FixedCost" closeOnTrainPurchase="1006">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1103" name="New York Central" abbrev="NYC" homeCell1="E19"
		homeLocation1="50" bgColor="Black" fgColor="White" tokens="4" tokenType="FixedCost">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1104" name="Chesapeake &amp; Ohio" abbrev="C&amp;O"
		homeCell1="F6" homeLocation1="17" bgColor="turquoise" fgColor="Black"
		tokens="3" tokenType="FixedCost">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1105" name="New York, New Haven &amp; Hartford"
		abbrev="NYNH" homeCell1="G19" homeLocation1="8" bgColor="Orange"
		fgColor="Black" tokens="2" tokenType="FixedCost">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1106" name="Boston &amp; Maine" abbrev="B&amp;M"
		homeCell1="E23" homeLocation1="21" mustBuyTrain="true" 
		bgColor="Light Green" fgColor="Black" homeColor="Black" tokens="2" tokenType="FixedCost">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1107" name="Canadian Pacific" abbrev="CP" homeCell1="A19"
		homeLocation1="17" bgColor="Red" fgColor="White" tokens="4" tokenType="FixedCost">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<Share id="1108" name="Erie" abbrev="Erie" homeCell1="E11"
		homeLocation1="17" homeLocation2="15" bgColor="Gold" fgColor="Black"
		homeColor="Black" tokens="3" tokenType="FixedCost">
		<Certificate director="YES" percentage="20" allowedOwners="IPO,Player" />
		<Certificate director="NO" percentage="10" quantity="8"
			allowedOwners="IPO,Player,BankPool" />
	</Share>
	<StartPacket>
		<Item row="1">
			<Certificate available="true" corporationId="1001" discountAmount="5" canBeBidOn="NO"></Certificate>
		</Item>
		<Item row="2">
			<Certificate available="true" corporationId="1002" discountAmount="0" canBeBidOn="YES"></Certificate>
		</Item>
		<Item row="3">
			<Certificate available="true" corporationId="1003" discountAmount="0" canBeBidOn="YES"></Certificate>
		</Item>
		<Item row="4">
			<Certificate available="true" corporationId="1004" discountAmount="0" canBeBidOn="YES"></Certificate>
		</Item>
		<Item row="5">
			<Certificate available="true" corporationId="1005" discountAmount="0" canBeBidOn="YES">
				<FreeCertificate corporationId="1101" percentage="10"/>
			</Certificate>
		</Item>
		<Item row="6">
			<Certificate available="true" corporationId="1006" discountAmount="0" canBeBidOn="YES">
				<FreeCertificate corporationId="1102" percentage="20"/>
			</Certificate>
		</Item>
	</StartPacket>
</Corporations>
